### PR TITLE
Separate Project/Document diagnostics

### LINKED ISSUE #1596: Compiler errors not associated with source show up in the ide on the first line
err

To reproduce:
- Use vs2015 preview 5 + the roslyn editor vsix'
- Create a new F# console project
- unload it and edit the proj file
- Add this:       ````<OtherFlags>$(OtherFlags) --times</OtherFlags>````
- Reload the project and build

It seems a bit timing sensitive, I had to exit and restart vs at least once  to repro it one time.

Kevin

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #1596 
@Microsoft/fsharp-compiler

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

File: vsintegration/tests/unittests/DocumentDiagnosticAnalyzerTests.fs [hunk 1]
```diff
@@ -372,3 +376,13 @@ type T =
 
 let g (t : T) = t.Count()
             """)
+            
+    [<Test>]
+    member public this.DocumentDiagnosticsDontReportProjectErrors_Bug1596() =
```
Comment (OmarTawfik) [inline vsintegration/tests/unittests/DocumentDiagnosticAnalyzerTests.fs]: @dsyme If you build the project, they will show up in output pane (from MSBuild) and error pane (from Roslyn service in this change). But they won't be highlighted on source code as the bug reported.
