### PR TITLE
Propose to use :> instead of :?> - fixes #1127

### LINKED ISSUE #1127: Improve error reporting: Wrong cast operator (:?> instead of :>)
Related to #1103 

# What

image

# Why
This error message is problematic for newcomers, especially ones from C#, because:
1. ```IDictionary<obj,obj>``` *is* compatible with ```Dictionary<obj, obj>```
2. C# only has one cast operator, and this works in C#:
```csharp
public static IDictionary<object, object> TestM() {
    return new Dictionary<object, object>();
}
```

# Possible solution
Before resorting to this error message, check if the left hand side can be statically cast to the type on the right, and if so, use a **"consider using the :> operator"** error message instead.

### PR DESCRIPTION
**Pull request by forki**
This is early work for #1127  and intended for first feedback round:

image

### CODE REVIEW

File: src/fsharp/ConstraintSolver.fs [hunk 1]
```diff
@@ -1912,6 +1913,13 @@ and private SolveTypSubsumesTypWithReport (csenv:ConstraintSolverEnv) ndeep m tr
     TryD (fun () -> SolveTypSubsumesTypKeepAbbrevs csenv ndeep m trace ty1 ty2)
          (fun res -> ErrorD (ErrorsFromAddingSubsumptionConstraint(csenv.g,csenv.DisplayEnv,ty1,ty2,res,m)))
 
+and private SolveTypSubsumesTypWithSpecialReport (csenv:ConstraintSolverEnv) ndeep m trace ty1 ty2 = 
+    TryD (fun () -> SolveTypSubsumesTypKeepAbbrevs csenv ndeep m trace ty1 ty2)
+         (fun res ->
+            match SolveTypSubsumesTypKeepAbbrevs csenv ndeep m trace ty2 ty1 with // test if we can cast other way around
```
Comment (dsyme) [inline src/fsharp/ConstraintSolver.fs]: I believe we want to undo the results of this new "solve" operation (regardless of whether it succeeds or not, using CollectThenUndo). We don't want the results of inference to be altered by giving better errors.

**Comment by forki** [comment]
image

**Comment by isaacabraham** [comment]
Just as a side question - why does the compiler give a warning only to then immediately afterwards give an error?

**Comment by forki** [comment]
I *think* this is an artifact of using fsi. @dsyme can you say more?

**Comment by isaacabraham** [comment]
Ah yes. It doesn't occur through e.g. VSCode.

**Comment by dsyme** [comment]
Nice. The ``TcRuntimeTypeTest`` path is hit on four kinds of syntax: 

* ``:? ty`` in patterns
* ``:? ty as ident`` in patterns
* ``downcast expr`` in expressions
* ``expr :?> ty`` 

I think the error message change is only suitable for the last case.  So that means you should pass in the ``ContextInfo.RuntimeTypeTest`` from each of the four callsites of ``TcRuntimeTypeTest`` and make sure we have tests for each of the case

Cheers!
Don

**Comment by forki** [comment]
image

@dsyme good catch ;-)

will add corresponding tests and fix that as well.

**Comment by forki** [comment]
image

that's better, right?

**Comment by forki** [comment]
tests added for all 4 cases.

File: tests/fsharp/typecheck/sigs/neg04.bsl [hunk 2]
```diff
@@ -69,55 +69,55 @@ neg04.fs(121,12,121,16): typecheck error FS0193: Type constraint mismatch. The t
...
 is not compatible with type
     IBar    
-The type 'R' is not compatible with the type 'IBar'
+
 
 neg04.fs(126,12,126,16): typecheck error FS0193: Type constraint mismatch. The type 
     U    
 is not compatible with type
     IBar    
-The type 'U' is not compatible with the type 'IBar'
```
Comment (forki) [inline tests/fsharp/typecheck/sigs/neg04.bsl]: Seems we always gave the error twice. Probably because it is so important to get your types right. 
Anyways, I fixed this as well.

File: tests/fsharp/typecheck/sigs/neg10.bsl [hunk 3]
```diff
@@ -113,7 +113,7 @@ neg10.fs(239,47,239,48): typecheck error FS0193: Type constraint mismatch. The t
     'b    
 is not compatible with type
     C    
-A type parameter is missing a constraint 'when 'b :> C'
```
Comment (forki) [inline tests/fsharp/typecheck/sigs/neg10.bsl]: this is still in line 118. so this is also a now removed duplication.

File: vsintegration/tests/unittests/Tests.LanguageService.ErrorList.fs [hunk 4]
```diff
@@ -177,26 +177,17 @@ let g (t : T) = t.Count()
...
+              "Possible overload: 'new : int -> X'." ]
 
         CheckErrorList content <|
             fun errors ->
                 Assert.AreEqual(3, List.length errors)
                 assertContains errors "No overloads match for method 'X'. The available overloads are shown below (or in the Error List window)."
                 for expected in expectedMessages do
-                    assertContains errors expected
+                   errors
+                   |> List.exists (fun e -> e.Message.StartsWith expected)
```
Comment (forki) [inline vsintegration/tests/unittests/Tests.LanguageService.ErrorList.fs]: this test was very flaky for me. so I made it a bit more robust.

File: tests/fsharpqa/Source/Warnings/UpcastFunctionInsteadOfDowncast.fs [hunk 5]
```diff
@@ -0,0 +1,9 @@
+// #Warnings
+//<Expects status="Error" span="(5,1)" id="FS3198">The conversion from Dictionary<obj,obj> to IDictionary<obj,obj> is a compile-time safe upcast, not a downcast. Consider using 'upcast' instead of 'downcast'.</Expects>
```
Comment (forki) [inline tests/fsharpqa/Source/Warnings/UpcastFunctionInsteadOfDowncast.fs]: this is a slightly different version of the hint. It#s not talking about operators

**Comment by dsyme** [comment]
OK, this looks good to go to me, assuming appveyor CI passes (I know Jenkins is having trouble right now).  I've removed the "WIP" .

**Comment by forki** [comment]
I rebased this.

**Comment by forki** [comment]
I think this is ready and the appveyor error is unrelated

**Comment by forki** [comment]
it's green and ready
