### PR TITLE
Symbols API: add IsNameGenerated to FSharpField

### LINKED ISSUE #3938: Symbols API: provide a way to check if a field name was generated
We need to check if a field name was generated (e.g. Item, Item2 in union cases, Data0, Data1 in exceptions) for symbols in source code.
This [commit](https://github.com/JetBrains/visualfsharp/commit/11e1b1066c3a8adf811d130f13160bee8df6bfd4) adds it, however not for fields defined in compiled assemblies. There're some other APIs we'd like to add and need for symbols defined in source code only as well. Should these APIs be generalized for IL types before opening PRs? (If yes, should info about field names be added to metadata?) Should they be added as is with a comment that it is for source-defined symbols only? Another option would be to add such APIs to a separate module.

### PR DESCRIPTION
**Pull request by auduchinok**
Fixes #3938.

I think it's not the best place to put the tests to as I've added a separate file for Symbol API tests in another PR, but that PR isn't merged yet. I think we should align tests later and split some of the existing files that cover lots of independent things.

### CODE REVIEW

File: src/fsharp/TypeChecker.fs [hunk 1]
```diff
@@ -15271,7 +15271,7 @@ module EstablishTypeDefinitionCores =
                                       let ty = names.[arg].Type
                                       let id = names.[arg].Ident
                                       let taccess = TAccess [envinner.eAccessPath]
-                                      yield NewRecdField false None id ty false false [(*no property attributes*)] [(*no field attributes *)] XmlDoc.Empty taccess (*compiler generated:*)true ]
+                                      yield NewRecdField false None id false ty false false [(*no property attributes*)] [(*no field attributes *)] XmlDoc.Empty taccess (*compiler generated:*)true ]
```
Comment (KevinRansom) [inline src/fsharp/TypeChecker.fs]: Good grief, we need to learn to use enums instead of Booleans for function arguments.
