### PR TITLE
Remove one "impossible" error

### LINKED ISSUE #5745: Illegal syntax in an active pattern produces an internal compiler error
Description: A specific kind of incorrect syntax in an active pattern definition causes an internal compiler error rather than a message specific to the error.

Repro Steps: Add the following code:

    open System.Text.RegularExpressions

    let (|USZipPlus4Code|_|) s =
        let m = Regex.Match(s, @"^(\d{5})\-(\d{4})$")
        if m.Success then
            USZipPlus4Code(x=m.Groups.[1].Value, 
                           y=m.Groups.[2].Value)
            |> Some
        else
            None

Expected: An error along the lines of:

'Active pattern bindings do not support field names.'

Actual: 

'error FS0073: internal error: impossible (Failure)'

Severity: minor.

Version: F# 4.5

Workaround: Use correct active pattern syntax. In this case, omit the x= and y=.

### PR DESCRIPTION
**Pull request by forki**
image

fixes #5745

### CODE REVIEW

File: src/fsharp/TypeChecker.fs [hunk 1]
```diff
@@ -5316,12 +5316,14 @@ and TcPat warnOnUpper cenv env topValInfo vFlags (tpenv, names, takenNames) ty p
...
-                                | Item.ExnCase tcref -> tcref.DisplayName
-                                | _ -> failwith "impossible"
-                            error(Error(FSComp.SR.tcUnionCaseConstructorDoesNotHaveFieldWithGivenName(caseName, id.idText), id.idRange))
+                            match item with
+                            | Item.UnionCase(uci, _) ->
+                                error(Error(FSComp.SR.tcUnionCaseConstructorDoesNotHaveFieldWithGivenName(uci.Name, id.idText), id.idRange))
+                            | Item.ExnCase tcref -> 
+                                error(Error(FSComp.SR.tcExceptionConstructorDoesNotHaveFieldWithGivenName(tcref.DisplayName, id.idText), id.idRange))
+                            | _ ->
+                                error(Error(FSComp.SR.tcConstructorDoesNotHaveFieldWithGivenName(id.idText), id.idRange))
```
Comment (matthid) [inline src/fsharp/TypeChecker.fs]: But this case is impossible, correct? Shouldn't we report this somehow?

File: src/fsharp/TypeChecker.fs [hunk 2]
```diff
@@ -8644,13 +8646,16 @@ and TcItemThen cenv overallTy env tpenv (item, mItem, rest, afterResolution) del
...
+                            else                                
+                                match item with
+                                | Item.UnionCase(uci, _) ->
+                                    error(Error(FSComp.SR.tcUnionCaseConstructorDoesNotHaveFieldWithGivenName(uci.Name, id.idText), id.idRange))
+                                | Item.ExnCase tcref ->
+                                    error(Error(FSComp.SR.tcExceptionConstructorDoesNotHaveFieldWithGivenName(tcref.DisplayName, id.idText), id.idRange))
+                                | Item.ActivePatternResult(_,_,_,_) ->
+                                    error(Error(FSComp.SR.tcActivePatternsDoNotHaveFields(), id.idRange))
+                                | _ -> 
+                                    error(Error(FSComp.SR.tcConstructorDoesNotHaveFieldWithGivenName(id.idText), id.idRange))
```
Comment (matthid) [inline src/fsharp/TypeChecker.fs]: Should we still report that this error message might need to be refined (in case it happens)? Would this be an advantage of `failwith "impossible"` here?

File: src/fsharp/TypeChecker.fs (hunk 1 above)
Comment (forki) [reply src/fsharp/TypeChecker.fs]: "impossible"

File: src/fsharp/TypeChecker.fs (hunk 2 above)
Comment (forki) [reply src/fsharp/TypeChecker.fs]: failwith "impossible" is arguably the worst you can do

File: src/fsharp/TypeChecker.fs (hunk 1 above)
Comment (matthid) [reply src/fsharp/TypeChecker.fs]: What I mean is that `item` is matched some lines above to be one of the two cases and `item` is immutable? This case means someone has changed something and missed to do some work. Removing `failwith` means the mistake will be spotted later (or not at all)

Comment (forki) [reply src/fsharp/TypeChecker.fs]: actually that is what already happend. the case was added and nobody changed the failwith "impossible"

File: src/fsharp/TypeChecker.fs (hunk 2 above)
Comment (matthid) [reply src/fsharp/TypeChecker.fs]: Yes ideally the code would be written in a way to not compile when written incorrectly, but if that cannot be achieved imho throwing is better than doing/reporting potentially incorrect messages

File: src/fsharp/TypeChecker.fs (hunk 1 above)
Comment (matthid) [reply src/fsharp/TypeChecker.fs]: But line above reads `| (Item.UnionCase _ | Item.ExnCase _) as item ->` how can this match another case?

Comment (forki) [reply src/fsharp/TypeChecker.fs]: it does not today. wait until someone adds the active pattern part ;-)

**Comment by forki** [comment]
@KevinRansom is something wrong with master? the error for linux build seems unrelated

**Comment by KevinRansom** [comment]
@forki not that I know.  The error is:
````
2018-10-09T12:23:11.3515703Z   /home/vsts/work/1/s/src/scripts/scriptlib.fsx(65,25): error FS0041: A unique overload for method 'GetFileName' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Path.GetFileName(path: ReadOnlySpan<char>) : ReadOnlySpan<char>, Path.GetFileName(path: string) : string [/home/vsts/work/1/s/tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj]
2018-10-09T12:23:11.3517355Z   /home/vsts/work/1/s/src/FSharpSource.targets(208,5): error MSB3073: The command "mono /home/vsts/work/1/s/packages/FSharp.Compiler.Tools.4.1.27/tools/fsi.exe --exec "/home/vsts/work/1/s/src/scripts/subst.fsx" --in:"/home/vsts/work/1/s/tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.dll.config" --out:"/home/vsts/work/1/s/tests/FSharp.Core.UnitTests/../../src/../release/net40/bin/FSharp.Core.UnitTests.dll.config" --pattern1:"FSCoreVersion" --replacement1:"4.5.0.0" --pattern2:"" --replacement2:"" " exited with code 1. [/home/vsts/work/1/s/tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj]
2018-10-09T12:23:11.3517711Z 
2
````
At this point I believe the script is running the built compiler, so I suppose there is some possibility they are related.

File: src/fsharp/TypeChecker.fs (hunk 2 above)
Comment (cartermp) [reply src/fsharp/TypeChecker.fs]: Actually I think even having a confusing error message is better than what existed. The current state of the world (without @forki's changes) paints the whole editor red if you use the incorrect code:

screen shot 2018-10-09 at 07 28 16

These internal errors are critical to root out given this, since it's pretty much undiagnosable where the user error is.

Comment (matthid) [reply src/fsharp/TypeChecker.fs]: Ok but imho we still should make sure the error message indicates this is not implemented and something which needs to be fixed if it occurs.
Otherwise users get wrong messages on their code which is arguably worse than a compiler crash

**Comment by cartermp** [comment]
@KevinRansom #5733 also has this error but with no compiler, so something's wrong in the mono FCS build.

File: src/fsharp/TypeChecker.fs (hunk 2 above)
Comment (forki) [reply src/fsharp/TypeChecker.fs]: we don't give a wrong message. We just give a very generic one

**Comment by KevinRansom** [comment]
@cartermp indeed it does.

**Comment by forki** [comment]
it's noew green after rebase
