### PR TITLE
Compiler doesn't allow exporting type abbreviations with wrong access modifier

### LINKED ISSUE #1158: Compiler allows exporting type abbreviations that mention private types
(Moved from https://github.com/fsharp/fsharp/issues/572)

The compiler doesn't currently prevent you exporting an alias for a private type, but it probably should. 

#### Repro steps

That is, given this code in an assembly:

```fsharp
module Library
type private Hidden = Hidden of unit
type Exported = Hidden
```

#### Actual behavior

Using this from *another assembly* can produce unexpected results:

```fsharp
// in the consuming executable...
open Library

[<EntryPoint>]
let main argv =
    let x : Exported = Unchecked.defaultof<_>
    printfn "%A" x
    0
```

Giving:

```
Unhandled Exception: System.MethodAccessException:
Attempt by method 'Program.main(System.String[])' to access method
'Microsoft.FSharp.Core.PrintfFormat`5<System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon>..ctor(System.String)' failed.
```

#### Expected behavior

The desired behaviour would be that a type abbreviation that mentions private types must also be private. This is how functions and "real" types work - neither of these are accepted:

```fsharp
type ExportedRealType = Bad of Hidden
let printExported (_ : Exported) = printfn "How did you get that?"
```

#### Related information 

Provide any related information 

* F#: 4.0 (Core 4.4.0.0)
* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: 4.5
* Editing Tools: VS2015 Update 2

### PR DESCRIPTION
**Pull request by forki**
fixes #1158

image

/cc @Porges

### CODE REVIEW

**Comment by forki** [comment]
Ok the error shows we actually rely on this in FSharp.Core.

in TaggedCollections.fs:

    type Map<'Key,'T> = Map<'Key, 'T, IComparer<'Key>>    
    type Set<'T> = Set<'T, IComparer<'T>>   

the types on the right are `ìnternal` but the types on the left are public.

**Comment by dsyme** [comment]
@forki That's in the compiler - those types can be made internal

**Comment by forki** [comment]
Ha, then that's nice solution ;-)

**Comment by forki** [comment]
this is ready for review

File: src/fsharp/TypeChecker.fs [hunk 1]
```diff
@@ -12651,7 +12651,10 @@ module MutRecBindingChecking =
                         let (TyconBindingDefn(containerInfo,newslotsOK,declKind,classMemberDef,m)) = defn
                         let (incrClassCtorLhsOpt,envForTycon,tpenv,recBindIdx,uncheckedBindsRev) = innerState
 
-                        if tcref.IsTypeAbbrev then error(Error(FSComp.SR.tcTypeAbbreviationsMayNotHaveMembers(),(trimRangeToLine m))) // ideally we'd have the 'm' of the type declaration stored here, to avoid needing to trim to line to approx
+                        if tcref.IsTypeAbbrev then
+                            // ideally we'd have the 'm' of the type declaration stored here, to avoid needing to trim to line to approx
+                            error(Error(FSComp.SR.tcTypeAbbreviationsMayNotHaveMembers(),(trimRangeToLine m)))
```
Comment (dsyme) [inline src/fsharp/TypeChecker.fs]: Why not ``tcref.Range``?

File: src/fsharp/TypeChecker.fs [hunk 2]
```diff
@@ -15042,9 +15043,13 @@ module EstablishTypeDefinitionCores =
             let acc = 
                 match tycon.TypeAbbrev with 
                 | None -> acc
-                | Some ty -> 
-                    //if not cenv.isSig && not cenv.haveSig && (tycon.Accessibility <> taccessPublic || tycon.TypeReprAccessibility <> taccessPublic) then 
-                    //   errorR(Error(FSComp.SR.tcTypeAbbreviationMustBePublic(),tycon.Range))
+                | Some ty ->
```
Comment (dsyme) [inline src/fsharp/TypeChecker.fs]: I think the right place for this check is ``CheckEntityDefn`` in ``PostInferenceChecks.fs`` using something like

    CheckTypeForAccess cenv env (fun () -> tycon.Name) tycon.Accessibility tycon.Range tycon.TypeAbbrev

This will check the type deeply, so ``type public X = List<MyPrivateType>`` will be detected correctly.

I'm really surprised we didn't have this check in, but there you go.  This will be a breaking change - so I guess we should consider making it a (strongly worded) warning.

**Comment by dsyme** [comment]
Left one comment above.  Rest of the code looks good.

File: src/fsharp/TypeChecker.fs (hunk 1 above)
Comment (forki) [inline src/fsharp/TypeChecker.fs]: I just added line break here

File: src/fsharp/TypeChecker.fs (hunk 2 above)
Comment (forki) [inline src/fsharp/TypeChecker.fs]: yes and I think it's sometimes even breaking already working code, right?

File: src/fsharp/TypeChecker.fs (hunk 1 above)
Comment (forki) [inline src/fsharp/TypeChecker.fs]: Ok changed that in 89243b5792be749911ec5a105780f8694343223b

Comment (forki) [inline src/fsharp/TypeChecker.fs]: ok reverted that one. It's showing the error in completely wrong location. We have a test that tries to augment string and it shows line no. that is not even in the augmentation file.

**Comment by forki** [comment]
Ok I changed the check to what you proposed. the message is slightly different but logical. thanks

**Comment by forki** [comment]
image

**Comment by dsyme** [comment]
Given that this is a breaking change as it stands, I think we do need to make this a deprecation warning rather than a hard error, and add some guidance to the error message, e.g. ``.... As of F# 4.1, the accessibility of type abbreviations is checked at compile-time. Consider adding 'internal' or 'private' to the type abbreviation``

**Comment by matthid** [comment]
I would suggest adding something like 'ignoring this warning might lead to runtime errors/exceptions' as well.

**Comment by dsyme** [comment]
@matthid - Yes, that's fair

**Comment by Porges** [comment]
Does F# have any formal policies around deprecation -- e.g. are there any paths for upgrading a warning to an error?

**Comment by dsyme** [comment]
@Porges F# itself has no formal policies, we assess each on a case-by-case basis. 

Microsoft (who ship the Visual F# packaging of F#) traditionally almost never do it, without 1-2 major version releases in-between.

**Comment by forki** [comment]
how about this?

image

**Comment by forki** [comment]
image

**Comment by forki** [comment]
ready for review.

**Comment by brodyberg** [comment]
Maybe: "Ignoring this warning and using Exported will lead to errors at
runtime."

**Comment by dsyme** [comment]
@forki conflicts need to be resolved

**Comment by forki** [comment]
done

**Comment by dsyme** [comment]
Thanks for the contribution (merging on behalf of @KevinRansom who is heads down in tuples)
