### PR TITLE
Don't fail with "impossible" compile error - fixes #1143

### LINKED ISSUE #1143: "Internal error FS0192 : impossible" in XmlDocWriter with CSV Type Provider
F# compiler fails with an "FS0192 impossible" compiler error somewhere in the XmlDocWriter logic.

It only occurs in relation to the CSV Type Provider, but even if the TP is buggy, I would not expect this to cause a compiler error.

#### Repro steps

The code to reproduce is available here (https://github.com/swlaschin/ImpossibleCompilerError) and can be reproduced in a small module ([MyModule.fs](https://github.com/swlaschin/ImpossibleCompilerError/blob/master/src/ImpossibleCompilerError/MyModule.fs))

#### Expected behavior

No compiler error!

#### Actual behavior

Here's a bit of the stack trace:

```
error FS0192 : internal error : impossible [\src\ImpossibleCompilerError\ImpossibleCompilerError.fsproj]

 Unhandled Exception: System.Exception: impossible
            at Microsoft.FSharp.Compiler.Tastops.typeEnc(TcGlobals g, FSharpList`1 gtpsType, FSharpList`1 gtpsMethod, TType ty)
            at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
            at Microsoft.FSharp.Compiler.Tastops.XmlDocArgsEnc(TcGlobals g, FSharpList`1 gtpsType, FSharpList`1 gtpsMethod, FSharpList`1 argTs)
            at Microsoft.FSharp.Compiler.Tastops.XmlDocSigOfVal(TcGlobals g, String path, Val v)
            at Microsoft.FSharp.Compiler.Driver.XmlDocWriter.doValSig@512(TcGlobals tcGlobals, String ptext, Val v)
            at Microsoft.FSharp.Compiler.Driver.XmlDocWriter.doValSig@512-1.Invoke(String ptext, Val v)
            at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
```

#### Known workarounds

Replace triple-slash doc strings with double-slash comment when the error occurs.

#### Related information 

* Windows 10
* NET framework: net452
* F# compiler: v4.0 (Visual Studio 2015)
* Fsharp.Core: 4.4.0.0
* FSharp.Data (2.2.5) (also fails with 2.3.0-beta2 )

### LINKED ISSUE #1144: MissingMethodException when opening solution in VS2015
Since yesterday I can't open VisualFSharp.sln anymore in VS2015 Update 2

image

I tried to rebuild the proto compiler and it succeeds from command line, but this still happens

### PR DESCRIPTION
**Pull request by forki**
@dsyme for #1143 we run into a missing pattern match (see diff). I copied the match case from the outer pattern match and the compile error is gone. I'm not sure if this is the correct fix...

/cc @swlaschin 

UPDATE: @dsyme suggested a better fix. PR updated

### CODE REVIEW

File: src/fsharp/TastOps.fs [hunk 1]
```diff
@@ -6762,7 +6762,8 @@ let typarEnc _g (gtpsType,gtpsMethod) typar =
 
 let rec typeEnc g (gtpsType,gtpsMethod) ty = 
     if verbose then  dprintf "--> typeEnc";
-    match (stripTyEqns g ty) with 
+    let stripped = stripTyEqns g ty
```
Comment (dsyme) [inline src/fsharp/TastOps.fs]: I believe this should just be  ``stripTyEqnsAndMeasureEqns`` here.

Comment (forki) [inline src/fsharp/TastOps.fs]: Ok let me check if it fixes it

Comment (forki) [inline src/fsharp/TastOps.fs]: yep that works. PR updated

**Comment by dsyme** [comment]
This looks good to me, the fix is very appropriate - we should always have been stripping units of measure here.

I wonder if we can add a test.  I know the original repro is complex though.
