### PR TITLE
Fix #nowarn "2003" not working - #3139

### LINKED ISSUE #3139: #nowarn “2003” doesn't disable FS2003
The repro code, below, compiled in a fresh console project in VS2017 (v15.2), fails to suppress the FS2003 warning (which the `#nowarn` directive should suppress). I'm targeting F# 4.1 (FSharp.Core 4.4.1.0).

We compile with "warnings as errors," so this is a strong issue. This is to be used in generated code, so `#nowarn` is far preferable to editing every F# project.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create an F# console project with VS2017.

2. Replace the program code with the code below.

3. Build
```
    open System.Reflection

    #nowarn "2003"
    [<assembly: AssemblyInformationalVersion("13.3.1.74-g5224f3b")>]

    do() // necessary for the assembly attribute

    [<EntryPoint>]
    let main argv = 0
```
#### Expected behavior

No FS2003 warning should be generated.

#### Actual behavior

An FS2003 warning was generated.

`FSC: warning FS2003: An System.Reflection.AssemblyInformationalVersionAttribute specified version '13.3.1.74-g5224f3b', but this value is invalid and has been ignored`

#### Known workarounds

Hand edit all your VS F# projects to ignore the warning in the project properties page. (Ew.)

#### Related information 

All testing was on .NET Framework 4.5 and 4.6.2 on Windows 10. Reproduces with both F# 4.0 and 4.1.

* Problem reproduced on VS 2017 15.2 26430.4.
* Problem reproduced on VS 2017 15.2 26430.6.
* Problem reproduced on VS 2015 14.0.25431.01 Update 3.

Also brought up on https://stackoverflow.com/q/44187146/83202

### PR DESCRIPTION
**Pull request by matthid**
Fixes #3139, by moving the warning emit of the warning into the type-checking phase. In detail the behavior changes are:

- Make sure the warning is triggered always (not only when `AssemblyVersionAttribute` is present)
- Make sure warning can be disabled via `#nowarn "2003"`
- Include the correct range of the problematic string

This means now warnings are emitted as:

`AssemblyInfo.fs(5,38): warning FS2003: An System.Reflection.AssemblyVersionAttribute specified version '5.0.0asdas', but this value is invalid and has been ignored` 

while previously they did not contain any range information

`warning FS2003: An System.Reflection.AssemblyVersionAttribute specified version '5.0.0asdas', but this value is invalid and has been ignored`

Also the ordering of the warnings might have changed. In order to compensate for the changed tests in `ProductVersion.fs` I added now ones in `tests/fsharp/tests.fs`.

### CODE REVIEW

**Comment by matthid** [comment]
The Ubuntu16.04 failure in https://github.com/Microsoft/visualfsharp/pull/4480/commits/5999fb6b5b6727ef1e50fa61adda3dc8cccd3388 is unrelated `The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/strawberryperl64/5.22.2.1/strawberryperl64.5.22.2.1.nupkg' has timed out after 100000ms.`, it is already reported here: https://github.com/Microsoft/visualfsharp/issues/3253

**Comment by matthid** [comment]
Seems like `AssemblyVersionAttribute` was previously reported via simple name and `System.Reflection.AssemblyInformationalVersionAttribute` and `System.Reflection.AssemblyFileVersionAttribute` via full name. 

Should we fix that here?

**Comment by matthid** [comment]
the ubuntu failure is not related, seems like nuget is on vacation this weekend

**Comment by dsyme** [comment]
@dotnet-bot Test Ubuntu16.04 Release_default Build please

File: src/fsharp/fsc.fs [hunk 1]
```diff
@@ -710,8 +710,7 @@ module AttributeHelpers =
              if deterministic && versionString.Contains("*") then
                  errorR(Error(FSComp.SR.fscAssemblyWildcardAndDeterminism(attribName, versionString), Range.rangeStartup))
              try Some (IL.parseILVersion versionString)
-             with e -> 
-                 warning(Error(FSComp.SR.fscBadAssemblyVersion(attribName, versionString), Range.rangeStartup))
+             with e ->
```
Comment (dsyme) [inline src/fsharp/fsc.fs]: Please add a comment that the warning will be reported by the TypeChecker.fs

File: src/fsharp/fsc.fs [hunk 2]
```diff
@@ -778,24 +777,21 @@ module MainModuleBuilder =
...
-    let fileVersion warn findStringAttr (assemblyVersion: ILVersionInfo) =
+    let fileVersion findStringAttr (assemblyVersion: ILVersionInfo) =
         let attrName = "System.Reflection.AssemblyFileVersionAttribute"
         match findStringAttr attrName with
         | None -> assemblyVersion
         | Some (AttributeHelpers.ILVersion(v)) -> v
-        | Some v -> 
-            warn(Error(FSComp.SR.fscBadAssemblyVersion(attrName, v), Range.rangeStartup))
-            //TODO compile error like c# compiler?
+        | Some _ ->
```
Comment (dsyme) [inline src/fsharp/fsc.fs]: Likewise here

File: src/fsharp/fsc.fs [hunk 3]
```diff
@@ -778,24 +777,21 @@ module MainModuleBuilder =
...
 
-    let productVersion warn findStringAttr (fileVersion: ILVersionInfo) =
+    let productVersion findStringAttr (fileVersion: ILVersionInfo) =
         let attrName = "System.Reflection.AssemblyInformationalVersionAttribute"
         let toDotted (v1, v2, v3, v4) = sprintf "%d.%d.%d.%d" v1 v2 v3 v4
         match findStringAttr attrName with
         | None | Some "" -> fileVersion |> toDotted
         | Some (AttributeHelpers.ILVersion(v)) -> v |> toDotted
         | Some v -> 
-            warn(Error(FSComp.SR.fscBadAssemblyVersion(attrName, v), Range.rangeStartup))
```
Comment (dsyme) [inline src/fsharp/fsc.fs]: Likewise here

File: tests/fsharp/core/versionAttributes/out.stderr.bsl [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+Warn2003_1.fs(7,6): warning FS0988: Main module of program is empty: nothing will happen when it is run
+Test 4=================================================
+
+Warn2003_2.fs(4,42): warning FS2003: An System.Reflection.AssemblyInformationalVersionAttribute specified version '5.0.0-beta024', but this value is invalid and has been ignored
+
+Warn2003_2.fs(6,6): warning FS0988: Main module of program is empty: nothing will happen when it is run
+Test 5=================================================
+
+Warn2003_3.fs(4,38): warning FS2003: An System.Reflection.AssemblyVersionAttribute specified version '5.0.0-beta024', but this value is invalid and has been ignored
```
Comment (dsyme) [inline tests/fsharp/core/versionAttributes/out.stderr.bsl]: The use of `An` in the error message looks wrong.  Perhaps change to `The attribute ....`

Comment (matthid) [reply tests/fsharp/core/versionAttributes/out.stderr.bsl]: Did I change this or is it something that makes sense changing (just curious)

File: src/fsharp/fsc.fs (hunk 1 above)
Comment (matthid) [reply src/fsharp/fsc.fs]: done.

File: src/fsharp/fsc.fs (hunk 2 above)
Comment (matthid) [reply src/fsharp/fsc.fs]: done.

File: src/fsharp/fsc.fs (hunk 3 above)
Comment (matthid) [reply src/fsharp/fsc.fs]: done.

File: tests/fsharp/core/versionAttributes/out.stderr.bsl (hunk 4 above)
Comment (matthid) [reply tests/fsharp/core/versionAttributes/out.stderr.bsl]: @dsyme Just to clarify: I change all messages to
`arning FS2003: The attribute System.Reflection.AssemblyInformationalVersionAttribute specified version '5.0.0-beta024', but this value is invalid and has been ignored`, correct?

Comment (dsyme) [reply tests/fsharp/core/versionAttributes/out.stderr.bsl]: great, thanks

File: src/fsharp/xlf/FSComp.txt.de.xlf [hunk 5]
```diff
@@ -5438,7 +5438,7 @@
         <note />
       </trans-unit>
       <trans-unit id="fscBadAssemblyVersion">
-        <source>An {0} specified version '{1}', but this value is invalid and has been ignored</source>
+        <source>The attribute {0} specified version '{1}', but this value is invalid and has been ignored</source>
         <target state="translated">Ein {0} gab Version '{1}' an, dieser Wert ist jedoch ungültig und wurde ignoriert.</target>
```
Comment (matthid) [inline src/fsharp/xlf/FSComp.txt.de.xlf]: Honestly this sounds just as bad as the previous English version. Should I change that as well or is somebody adapting all translations?

/cc @forki because I think he has fought for a better translation before.

File: tests/fsharp/core/versionAttributes/out.stderr.bsl (hunk 4 above)
Comment (matthid) [reply tests/fsharp/core/versionAttributes/out.stderr.bsl]: ok done, lets see if it is still green...

**Comment by matthid** [comment]
@dsyme should be use a `negXX` test here as well?

**Comment by matthid** [comment]
@dsyme OK I got it working again with the new message :)

**Comment by matthid** [comment]
@dsyme Is there still something blocked on my side? At least initially it looked simple enough

**Comment by KevinRansom** [comment]
@matthid Thank you for this
