### PR TITLE
Better error message when specializing generic abstract type with unit

### LINKED ISSUE #35: Improve error message when attempting to override generic return type with unit
[originally from  [Connect](http://connect.microsoft.com/VisualStudio/feedback/details/808164/implementing-generic-methods-unit-problems)] 

 This kind of F# code doesn't work when passing unit as a type argument. If this is an intentional design restriction, the error message should reflect this.

```fsharp
type EDF<'S> =
    abstract member Apply : int -> 'S
type SomeEDF1 () =
    interface EDF<int> with
        member this.Apply d = // OK
            123
type SomeEDF2 () =
    interface EDF<unit> with
        member this.Apply d = 
            // [ERROR] The member 'Apply : int -> unit' does not have the correct type to override the corresponding abstract method.
            ()
```

> comments
> dsyme wrote May 29, 2014 at 6:58 AM [x] 
> Yes, for F# 3.x this is an intentional design restriction, see  http://stackoverflow.com/questions/4485445/f-interface-inheritance-failure-due-to-unit/4485677#4485677 for a longer analysis.

> You might like to add an issue to  http://fslang.uservoice.com to track this, as the F# language spec and implementation could in theory be adjusted to do the appropriate insertion of a "unit" value in the implementation of the override.

> I agree that the error message should be improved here. 

>> dsyme wrote May 29, 2014 at 7:17 AM [x] 
>>To summarize - in F#, an abstract slot with declared return type of "unit" gets compiled in .NET IL as a return type of "void". In contrast, an abstract slot with declared return type of "T" gets compiled in .NET IL as a generic return type of "T", which when T is instantiated by "unit" becomes "unit". This means these two slots have logically different characteristics. This difference is one of the few places where the unit<->void translation performed by F# is visible and yes, it affects the overriding rules of the F# language.

>> @antofik asked about the compiler implementation here, specifically IsExactMatch and the check "returnTypesAEquiv" (here in the GitHub code:  https://github.com/fsharp/fsharp/blob/6ac6318858da25fe4f1d4728901c5824e9f3bf3a/src/fsharp/tastops.fs#L874 - when will codeplex support links to individual lines :) ).

>> This operation compares optional TType values representing the return type of the member. None indicates that the return type is logically "void" from the perspective of F# overriding rules, Some(unit-type) or Some (T) indicates the return type is logically "unit" or "T" from the perspective of F# overriding rules.

>> In terms on nomenclature in the compiler:
>>* "CompiledForm" of a method signature means that return types are TType options, 
 "None = type void", and "Some(T) = type T", and "Some(T) under substitution T-->unit = type unit". 
>>* "FSharpForm" of a method signature means that return types are TType, and where "void" doesn't occur at all

>> Note that in the debugger, "None" shows as "null".

>>> dsyme wrote May 29, 2014 at 7:21 AM [x] 
>>> To add a better error message, the logical place to put it would be here:  https://github.com/fsharp/fsharp/blob/6ac6318858da25fe4f1d4728901c5824e9f3bf3a/src/fsharp/typrelns.fs#L1191

>>> "IsExactMatch" would need to be duplicated and adjusted to a "IsExactMatchUpToInstantiatedUnitReturnType". If an override exists satisfying that predicate, then a better error message can then be given, much as for code already present to give a better error message when there is an override satisfying IsPartialMatch or IsNameMatch.
>>> Cheers!
>>> don

>>>> latkin wrote Jun 20, 2014 at 6:24 AM [x] 

>>>> Updating the title to capture specific goal for short term. fslang uservoice can be used to track this as a potential change to the language itself.

### PR DESCRIPTION
**Pull request by smoothdeveloper**
Attempt to fix #35

I'll need some guidance in terms of where to add tests and of course if there is anything wrong with the matching I'm doing / assumptions I'm taking.

I'm concerned the matching might yield false positive if there are cases where using `unit` as a generic type argument would be valid, but this is difficult for me to reason about as of now.

Also looking for better ideas for the error message.

### CODE REVIEW

**Comment by forki** [comment]
regarding tests: tests\fsharpqa\Source\Warnings\env.lst is now a dumping ground for tests that check error messages. I think it would be ok to add it there

File: src/fsharp/CompileOps.fs [hunk 1]
```diff
@@ -1144,15 +1145,32 @@ let OutputPhasedErrorR (os:System.Text.StringBuilder) (err:PhasedError) =
...
+              let rec hasUnitTType_app (types: TType list) =
+                  match types with
+                  | TType_app (maybeUnit, []) :: ts -> 
+                      match maybeUnit.TypeAbbrev with
+                      | Some ttype when Tastops.isUnitTy g ttype -> true
+                      | _ -> hasUnitTType_app ts
+                  | _ :: ts -> hasUnitTType_app ts
+                  | [] -> false
+
+              match minfoVirt.EnclosingType with
```
Comment (forki) [inline src/fsharp/CompileOps.fs]: most simmilar pattern matches call striptypEqns - maybe @dsyme can tell if it's needed here

**Comment by smoothdeveloper** [comment]
thanks @forki, I'll pay a look and try to add few tests supposed to trigger that new message.

**Comment by smoothdeveloper** [comment]
Mmmh reading details @dsyme left in the ancient conversation and my proposed fix is not really handling things at the level he was intending the changes to happen but later down the road, although it looks simpler (if that doesn't raise false positives), maybe it doesn't follow the normal conventions for deciding of errors, but there are few other conditionals to decide which error message to raise where I've added the logic.

> To add a better error message, the logical place to put it would be here: https://github.com/fsharp/fsharp/blob/6ac6318858da25fe4f1d4728901c5824e9f3bf3a/src/fsharp/typrelns.fs#L1191

> "IsExactMatch" would need to be duplicated and adjusted to a "IsExactMatchUpToInstantiatedUnitReturnType". If an override exists satisfying that predicate, then a better error message can then be given, much as for code already present to give a better error message when there is an override satisfying IsPartialMatch or IsNameMatch.

I'm trying to see if other cases would trigger the initial / new error messages, this compiles fine with and without the change:

```fsharp
type Foo<'t> =
  abstract member Bar : 't -> int

type Bar() =
  interface Foo<unit> with
    member x.Bar _ = 1
```

I'll look if fsharpqa also has tests checking no error / warning shows up to add that case.

If anyone knows of additional cases I should account for, that would be great.

File: tests/fsharpqa/Source/Conformance/TypesAndTypeConstraints/TypeParameterDefinitions/UnitSpecialization.fs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// #UnitGenericAbstractType 
+//<Expects status=success></Expects>
```
Comment (enricosada) [inline tests/fsharpqa/Source/Conformance/TypesAndTypeConstraints/TypeParameterDefinitions/UnitSpecialization.fs]: it's not an error (this sintax is supported), but can you pls write that as xml like (supported too)? 

```
//<Expects status="success"></Expects>
```

i am trying to convert the suite to nunit, and to simplify i'll need to convert that as xml like (easier to parse, validate)

File: tests/fsharpqa/Source/ErrorMessages/UnitGenericAbstractType/E_UnitGenericAbstractType1.fs [hunk 3]
```diff
@@ -0,0 +1,9 @@
+// #ErrorMessages #UnitGenericAbstractType 
+//<Expects status="error" span="(7,21)" id="FS0017">The member 'Apply : int -> unit' is specialized with 'unit' but 'unit' can't be used as return type of an abstract method parameterized on return type.\.</Expects>
```
Comment (enricosada) [inline tests/fsharpqa/Source/ErrorMessages/UnitGenericAbstractType/E_UnitGenericAbstractType1.fs]: the regex at end `.\.` is right? is not just `\.`?
like that parse any character followed by dot, instead of just a dot

But i just tried with this https://regex101.com/r/oG5sD1/1 online regex, if you remove the `.` before `\.` works.

Comment (smoothdeveloper) [inline tests/fsharpqa/Source/ErrorMessages/UnitGenericAbstractType/E_UnitGenericAbstractType1.fs]: @enricosada thanks!

I need more time to dig into TESTGUIDE.md but it seems there is a lot of implicit knowledge about how those tests are defined which is undocumented.

I tried to follow stuff around (the wrong xml stuff was copied from another file) without knowing exactly how that works.

**Comment by smoothdeveloper** [comment]
@KevinRansom or @dsyme could we get

**Comment by smoothdeveloper** [comment]
@KevinRansom or @dsyme could we get a review on proposed fix and some direction for the error message?

**Comment by KevinRansom** [comment]
@dsyme 
This looks good to me, but I may be missing something, could you take a look please.

Kevin

**Comment by KevinRansom** [comment]
Thank you for taking care of this

Kevin
