### PR TITLE
Fix 'Object reference not set to an instance of an object' in FSI when .ToString() returns null

### LINKED ISSUE #706: error FS0193: internal error: Object reference not set to an instance of an object.
_From @fwaris on October 28, 2015 18:36_

The error can be reproduced by running the following two lines (need sql server installed):

#r @"C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\Microsoft.AnalysisServices.DLL"
let s = new Microsoft.AnalysisServices.Server()

Basically the 'printing' system cannot handle the layout for "s" above.

The workaround for now is to add a custom printer:
fsi.AddPrintTransformer(fun (s:Microsoft.AnalysisServices.Server)-> box "Server")

I tried to trace through the fsi print layout code but since I am not familiar with it, I could not spot the place with the NRE is being raised.

_Copied from original issue: fsharp/fsharp#509_

### PR DESCRIPTION
**Pull request by rojepp**
Fixes #706.

### CODE REVIEW

File: src/utils/sformat.fs [hunk 1]
```diff
@@ -1194,7 +1194,7 @@ namespace Microsoft.FSharp.Text.StructuredFormat
             | :? bool   as b -> (if b then "true" else "false")
             | :? char   as c -> "\'" + formatChar true c + "\'"
             | _ -> try  let text = obj.ToString()
-                        text
+                        if text = null then "" else text
```
Comment (forki) [inline src/utils/sformat.fs]: Please use isNull or pattern matching. FSLint would complain ;-)

Comment (rojepp) [inline src/utils/sformat.fs]: isNull is not available in proto, and pattern matching here seems ugly. :) 
Surely we don't have to do everything FSLint says? FSLint would probably find tons of issues in this code base.

Comment (forki) [inline src/utils/sformat.fs]: No we do not care about FSLint, but I remember reading isNull and pattern
matching against null makes perf difference in F#. Not sure if this is the
case in proto,  but the only reason fslint is suggesting pattern matching
and isNull is because of perf.

Comment (rojepp) [inline src/utils/sformat.fs]: I actually checked that, and, at least for string, this comparison just compiles to `string.Equals(text, null)` which should be optimal.

Comment (forki) [inline src/utils/sformat.fs]: Cool.

**Comment by KevinRansom** [comment]
Looks good to me.  Thanks for taking care of this.
