### PR TITLE
better fix for #5369

### LINKED ISSUE #5369: Internal type check error seen in production code
image

that looks weird

### PR DESCRIPTION
**Pull request by dsyme**
This is the better fix #5369, improving https://github.com/Microsoft/visualfsharp/pull/5388

### CODE REVIEW

File: src/fsharp/TastPickle.fs [hunk 1]
```diff
@@ -1566,11 +1575,15 @@ let _ = fill_p_ty (fun ty st ->
...
     | TType_fun (d,r)                   -> 
         p_byte 3 st
-        p_ty d st
-        st.isStructThisArgPos <- false
+        // Note, the "this" argument may be found in the domain position of a function type, so propagate the isStructThisArgPos value
+        p_ty2 isStructThisArgPos d st
         p_ty r st
     | TType_var r                       -> p_byte 4 st; p_tpref r st
-    | TType_forall (tps,r)              -> p_byte 5 st; p_tup2 p_tyar_specs p_ty (tps,r) st
+    | TType_forall (tps,r)              ->
```
Comment (KevinRansom) [inline src/fsharp/TastPickle.fs]: @dsyme was this scenario not covered by the previous fix?

**Comment by TIHan** [comment]
Looks clean to me!
